[core]
NUM_THREADS = 4
NUM_WARPS = 16
NUM_FPU_BLOCKS = 1
NUM_ALU_BLOCKS = 1
NUM_LSU_BLOCKS = 1
ISSUE_WIDTH = 1

[cache]
DCACHE_SIZE = 65536
SMEM_SIZE = 4096
L2_ENABLE = true

[simulation]
driver = "simx"
cores = 1
clusters = 1
matrix_size = 64